# General settings
title: Mechanics at Civil Engineering
author:  Tom van Woudenberg from Delft University of Technology, built with <a href="https://teachbooks.tudelft.nl/">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt="">
email: T.R.vanWoudenberg@tudelft.nl
logo: images/logo.png

repository:
  branch: publish
  path_to_book: book

html:
  favicon : "images/favicon.ico"
  baseurl :  "https://teachbooks.github.io/Structural-Mechanics-4/"
  home_page_in_navbar       : true

# Execute notebooks when building
execute:
  execute_notebooks: 'off'

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/TeachBooks/Structural-Mechanics-4"
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
          thebe: true

  extra_extensions:
    - sphinx.ext.imgconverter
    - download_link_replacer
    - jupyterbook_patches


bibtex_bibfiles:
  - references.bib
